### Upadate an existing patient entity
PUT localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
content-type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "address": "123 Main St",
  "dateOfBirth": "1990-01-01"
}
###